version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb # 이미지를 자체 빌드하기 위해 작성
    restart: always
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - inception
    expose: #expose는 호스트 내부의 다른 컨테이너들만 액세스 가능 
      - "3306"
    env_file:
      - .env
    
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db_vol:
    name: db_vol
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/junylee/data/mariadb